channels:
  - conda-forge
  - defaults
dependencies:
  - pyogrio
  - shapely>=2
  - geopandas
  - pyrosm
  - scikit-image
  - opencv
  - rasterio
  - gdal
  - pytest
  - pytest-cov
  - matplotlib
  - pyyaml