channels:
  - conda-forge
  - defaults
dependencies:
  - pyogrio
  - shapely>=2
  - geopandas
  - pyrosm
  - scikit-image
  - opencv
  - pytest
  - pytest-cov
  - matplotlib
  - pyyaml
  - pip:
    - affine==2.4.0
    - aiobotocore==2.9.0
    - aiohttp==3.9.1
    - aioitertools==0.11.0
    - aiosignal==1.3.1
    - async-timeout==4.0.3
    - attrs==23.1.0
    - botocore==1.33.13
    - bounded-pool-executor==0.0.3
    - certifi==2023.7.22
    - charset-normalizer==3.3.2
    - click==8.1.7
    - click-plugins==1.1.1
    - cligj==0.7.2
    - configupdater==3.1.1
    - contourpy==1.1.1
    - cycler==0.12.1
    - earthaccess==0.8.2
    - ephem==4.1.5
    - fiona==1.8.21
    - fonttools==4.44.0
    - frozenlist==1.4.1
    - fsspec==2023.12.2
    - gdal==3.5.0
    - geographiclib==2.0
    - geopandas==0.13
    - geopy==2.4.0
    - idna==3.6
    - imageio==2.32.0
    - importlib-metadata==6.8.0
    - importlib-resources==6.1.0
    - jmespath==1.0.1
    - kiwisolver==1.4.5
    - matplotlib==3.7.3
    - multidict==6.0.4
    - multimethod==1.10
    - numpy==1.24.4
    - packaging
    - pandas
    - pillow
    - platformdirs==3.11.0
    - pqdm==0.2.0
    - pyparsing==3.1.1
    - pyproj==3.5.0
    - pyscaffold==4.5
    - python-cmr==0.9.0
    - python-dateutil==2.8.2
    - pytz==2023.3.post1
    - requests==2.31.0
    - s3fs==2023.12.2
    - scipy
    - setuptools-scm==8.0.4
    - shapely==2.0.2
    - six==1.16.0
    - snuggs==1.4.7
    - timezonefinder
    - tinynetrc==1.3.1
    - tomli==2.0.1
    - tomlkit==0.12.2
    - tqdm==4.66
    - typing-extensions==4.8.0
    - tzdata==2023.3
    - urllib3==1.26.18
    - wrapt==1.16.0
    - yarl==1.9.4
    - zipp==3.17.0